import { NextResponse } from 'next/server';
import { fetchCVEDetails } from '@/lib/nvd';

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const target = searchParams.get('target') || 'http://localhost:3001';

  const scanTimestamp = new Date().toISOString();

  // ═══ FASE 1: Simulación de Spider/Crawler ═══
  const spiderResults = [
    { url: `${target}/`, method: 'GET', status: 200, type: 'page' },
    { url: `${target}/search`, method: 'GET', status: 200, type: 'page' },
    { url: `${target}/search?q=test`, method: 'GET', status: 200, type: 'dynamic' },
    { url: `${target}/api/login`, method: 'POST', status: 401, type: 'api' },
    { url: `${target}/_next/static/`, method: 'GET', status: 200, type: 'asset' },
    { url: `${target}/favicon.ico`, method: 'GET', status: 200, type: 'asset' },
  ];

  // ═══ FASE 2: Alertas de Vulnerabilidades (OWASP ZAP + Mozilla Observatory + Nast API) ═══
  const mockAlerts = [
    {
      id: 'alert-1',
      source: 'OWASP ZAP (Active Scan)',
      cweId: 'CWE-79',
      cveId: 'N/A',
      owaspCategory: 'A03:2021 – Injection',
      name: 'Cross-site scripting reflected (XSS)',
      severity: 'Medium',
      riskScore: 6.5,
      description: 'El Cross-site scripting es una vulnerabilidad que aprovecha la falta de mecanismos de filtrado en los campos de entrada, permitiendo el ingreso de datos sin validación alguna, aceptando el envío de scripts maliciosos.',
      affectedUrl: `${target}/index.php?pagina=paginas_tipo_riesgo`,
      evidence: "Parámetro 'pagina' reflejado sin sanitización.",
      timestamp: scanTimestamp,
      cia: { confidentiality: true, integrity: true, availability: false },
      effort: { complexity: 'MEDIA', cost: 'BAJO' },
      incidences: 4,
      riskFactors: {
        threat: { a1: 3, a2: 9, a3: 4, a4: 4 },
        vulnerability: { v1: 7, v2: 9, v3: 5, v4: 8 },
        technical: { t1: 2, t2: 0, t3: 0, t4: 7 },
        business: { n1: 1, n2: 1, n3: 5, n4: 3 },
      },
    },
    {
      id: 'alert-2',
      source: 'Mozilla Observatory',
      cweId: 'CWE-614',
      cveId: 'N/A',
      owaspCategory: 'A05:2021 – Security Misconfiguration',
      name: 'TLS cookie without Secure and HTTPOnly flag set',
      severity: 'Medium',
      riskScore: 6.0,
      description: 'Las cookies de sesión no tienen establecidos los flags Secure y HTTPOnly, lo que permite que sean interceptadas en canales no cifrados o accedidas mediante scripts maliciosos (XSS).',
      affectedUrl: target,
      evidence: "Set-Cookie header sin 'Secure' ni 'HttpOnly'.",
      timestamp: scanTimestamp,
      cia: { confidentiality: true, integrity: true, availability: false },
      effort: { complexity: 'BAJA', cost: 'BAJO' },
      incidences: 1,
      riskFactors: {
        threat: { a1: 3, a2: 9, a3: 4, a4: 4 },
        vulnerability: { v1: 9, v2: 9, v3: 6, v4: 8 },
        technical: { t1: 2, t2: 0, t3: 0, t4: 7 },
        business: { n1: 1, n2: 1, n3: 5, n4: 3 },
      },
    },
    {
      id: 'alert-3',
      source: 'OWASP ZAP (Passive Scan)',
      cweId: 'CWE-209',
      cveId: 'N/A',
      owaspCategory: 'A09:2021 – Security Logging and Monitoring Failures',
      name: 'Error Handling',
      severity: 'Low',
      riskScore: 3.5,
      description: 'El manejo de errores del servidor revela información técnica (stack traces, versiones) que puede ser utilizada por un atacante para perfilar el sistema.',
      affectedUrl: `${target}/api/data`,
      evidence: "Respuesta 500 devuelve stack trace de Node.js.",
      timestamp: scanTimestamp,
      cia: { confidentiality: true, integrity: false, availability: false },
      effort: { complexity: 'BAJA', cost: 'BAJO' },
      incidences: 2,
      riskFactors: {
        threat: { a1: 2, a2: 5, a3: 3, a4: 3 },
        vulnerability: { v1: 5, v2: 4, v3: 4, v4: 5 },
        technical: { t1: 1, t2: 1, t3: 0, t4: 2 },
        business: { n1: 0, n2: 1, n3: 2, n4: 1 },
      },
    },
    {
      id: 'alert-4',
      source: 'OWASP ZAP (Spider)',
      cweId: 'CWE-200',
      cveId: 'N/A',
      owaspCategory: 'A01:2021 – Broken Access Control',
      name: 'Full path disclosure',
      severity: 'Low',
      riskScore: 3.0,
      description: 'Se ha detectado la exposición de la ruta completa del sistema de archivos en el servidor, lo que facilita ataques dirigidos al sistema operativo.',
      affectedUrl: `${target}/tmp/log.txt`,
      evidence: "Mensaje de error revela 'C:\\Users\\Usuario\\Documents\\...'",
      timestamp: scanTimestamp,
      cia: { confidentiality: true, integrity: false, availability: false },
      effort: { complexity: 'BAJA', cost: 'BAJO' },
      incidences: 1,
      riskFactors: {
        threat: { a1: 2, a2: 5, a3: 3, a4: 3 },
        vulnerability: { v1: 6, v2: 4, v3: 3, v4: 4 },
        technical: { t1: 1, t2: 0, t3: 0, t4: 1 },
        business: { n1: 0, n2: 1, n3: 1, n4: 1 },
      },
    },
    {
      id: 'alert-5',
      source: 'Nast API',
      cweId: 'CWE-200',
      cveId: 'N/A',
      owaspCategory: 'A01:2021 – Broken Access Control',
      name: 'Internal IP disclosure',
      severity: 'Low',
      riskScore: 2.5,
      description: 'El servidor revela direcciones IP internas en las cabeceras de respuesta o en el contenido HTML, facilitando el reconocimiento de la red interna.',
      affectedUrl: target,
      evidence: "Header 'X-Backend-Server' revela IP 10.0.0.5.",
      timestamp: scanTimestamp,
      cia: { confidentiality: true, integrity: false, availability: false },
      effort: { complexity: 'BAJA', cost: 'BAJO' },
      incidences: 5,
      riskFactors: {
        threat: { a1: 2, a2: 4, a3: 3, a4: 3 },
        vulnerability: { v1: 6, v2: 3, v3: 3, v4: 4 },
        technical: { t1: 1, t2: 0, t3: 0, t4: 1 },
        business: { n1: 0, n2: 1, n3: 1, n4: 1 },
      },
    },
    {
      id: 'alert-6',
      source: 'OWASP ZAP (Passive Scan)',
      cweId: 'CWE-1104',
      cveId: 'CVE-2020-11022',
      owaspCategory: 'A06:2021 – Vulnerable and Outdated Components',
      name: 'Vulnerable JavaScript library',
      severity: 'Low',
      riskScore: 4.0,
      description: 'Se detectó el uso de una librería de JavaScript (jQuery 1.12) con vulnerabilidades conocidas de XSS.',
      affectedUrl: `${target}/js/jquery.min.js`,
      evidence: "Versión detectada: 1.12.4. CVE-2020-11022 asociado.",
      timestamp: scanTimestamp,
      cia: { confidentiality: true, integrity: true, availability: false },
      effort: { complexity: 'MEDIA', cost: 'BAJO' },
      incidences: 9,
      riskFactors: {
        threat: { a1: 3, a2: 6, a3: 4, a4: 4 },
        vulnerability: { v1: 7, v2: 6, v3: 5, v4: 6 },
        technical: { t1: 2, t2: 1, t3: 0, t4: 3 },
        business: { n1: 1, n2: 1, n3: 3, n4: 2 },
      },
    },
    {
      id: 'alert-7',
      source: 'Mozilla Observatory',
      cweId: 'CWE-327',
      cveId: 'N/A',
      owaspCategory: 'A02:2021 – Cryptographic Failures',
      name: 'TLS v1.0 / v1.1 protocol detected',
      severity: 'Low',
      riskScore: 3.0,
      description: 'El servidor permite conexiones utilizando protocolos TLS obsoletos (1.0 y 1.1), los cuales son vulnerables a ataques criptográficos.',
      affectedUrl: target,
      evidence: "Handshake exitoso con TLS 1.0.",
      timestamp: scanTimestamp,
      cia: { confidentiality: true, integrity: false, availability: false },
      effort: { complexity: 'BAJA', cost: 'BAJO' },
      incidences: 1,
      riskFactors: {
        threat: { a1: 3, a2: 5, a3: 3, a4: 3 },
        vulnerability: { v1: 6, v2: 5, v3: 4, v4: 4 },
        technical: { t1: 2, t2: 0, t3: 0, t4: 2 },
        business: { n1: 1, n2: 1, n3: 2, n4: 1 },
      },
    },
    {
      id: 'alert-op1',
      source: 'OWASP ZAP (Passive Scan)',
      cweId: 'CWE-200',
      cveId: 'N/A',
      owaspCategory: 'A01:2021 – Broken Access Control',
      name: 'HTTP TRACE / TRACK Methods Allowed',
      severity: 'Low',
      riskScore: 1.5,
      description: 'Oportunidad de Mejora: Los métodos HTTP TRACE y TRACK están habilitados, lo que podría permitir ataques de Cross-Site Tracing (XST).',
      affectedUrl: target,
      evidence: "Método TRACE habilitado en el servidor.",
      timestamp: scanTimestamp,
      cia: { confidentiality: true, integrity: false, availability: false },
      effort: { complexity: 'BAJA', cost: 'BAJO' },
      incidences: 1,
      riskFactors: {
        threat: { a1: 1, a2: 3, a3: 2, a4: 2 },
        vulnerability: { v1: 4, v2: 2, v3: 2, v4: 3 },
        technical: { t1: 1, t2: 0, t3: 0, t4: 1 },
        business: { n1: 0, n2: 0, n3: 1, n4: 1 },
      },
    },
    {
      id: 'alert-op2',
      source: 'Nast API',
      cweId: 'CWE-200',
      cveId: 'N/A',
      owaspCategory: 'A01:2021 – Broken Access Control',
      name: 'Backup files / Test files / Old files',
      severity: 'Low',
      riskScore: 1.0,
      description: 'Oportunidad de Mejora: Se detectaron archivos de respaldo o temporales (config.php.bak) expuestos en el servidor.',
      affectedUrl: `${target}/config.php.bak`,
      evidence: "Archivo .bak accesible.",
      timestamp: scanTimestamp,
      cia: { confidentiality: true, integrity: false, availability: false },
      effort: { complexity: 'BAJA', cost: 'BAJO' },
      incidences: 1,
      riskFactors: {
        threat: { a1: 1, a2: 2, a3: 1, a4: 2 },
        vulnerability: { v1: 3, v2: 1, v3: 1, v4: 2 },
        technical: { t1: 1, t2: 0, t3: 0, t4: 1 },
        business: { n1: 0, n2: 0, n3: 1, n4: 1 },
      },
    },
  ];

  // Enriquecer con datos de NVD si hay CVE
  for (const alert of mockAlerts) {
    if (alert.cveId && alert.cveId !== 'N/A') {
      (alert as any).nvdData = await fetchCVEDetails(alert.cveId);
    }
  }

  const summary = {
    critical: mockAlerts.filter(a => a.severity === 'Critical').length,
    high: mockAlerts.filter(a => a.severity === 'High').length,
    medium: mockAlerts.filter(a => a.severity === 'Medium').length,
    low: mockAlerts.filter(a => a.severity === 'Low').length,
  };

  return NextResponse.json({
    target,
    scanEngine: 'OWASP ZAP v2.15.0 + Mozilla Observatory v3.0',
    scanDate: scanTimestamp,
    totalAlerts: mockAlerts.length,
    spiderResults,
    summary,
    alerts: mockAlerts,
    observatoryGrade: 'F',
    observatoryScore: 0,
  });
}
